### ISSUE TITLE
`Trilogy.connect` not working in Staging and Production environments.

### ISSUE THREAD

**Issue by joshuapinter** [trilogy-libraries/trilogy#149]
### In Staging and Production

```ruby
config = Rails.configuration.database_configuration[ Rails.env ]
connection = Trilogy.new( config )
#=> .../trilogy-2.6.1/lib/trilogy.rb:18:in `_connect': No such file or directory - trilogy_connect - unable to connect to /tmp/mysql.sock (Trilogy::SyscallError::ENOENT)
```

### In Development

```ruby
config = Rails.configuration.database_configuration[ Rails.env ]
connection = Trilogy.new( config )
#=> <Trilogy:0x000000013a9de1e0
```

The configs between the environments are similar with just different `database`, `username`, `password` and `host` values.

Moreover, the actual Rails application (i.e. `ActiveRecord`) works just fine in all environments using Trilogy.

Any thoughts on this?

Thanks!

**Comment by bensheldon** [comment]
Is your production database available via a socket file on that same host? `unable to connect to /tmp/mysql.sock (Trilogy::SyscallError::ENOENT)` 

It looks like your configuration may still have Trilogy connecting via a file-based socket rather than remotely over the network and/or port `3306`.

**Comment by joshuapinter** [comment]
Thanks for the reply @bensheldon. 

I don't think that's it because the actual app works just fine. As an example here is my staging environment config: 

```yml
staging:
  database:  redacted
  username:  redacted
  password:  redacted
  adapter:   trilogy
  collation: utf8mb4_unicode_ci
  encoding:  utf8mb4
  host:      redacted
  pool:      20
  port:      3306
  reconnect: true
  variables:
    sql_mode: TRADITIONAL
```

Is there something special with `Trilogy.connect` that we need to force it to use the `host` and `port` instead of a socket file?
