### ISSUE TITLE
Performance drop switching from mysql2

### ISSUE THREAD

**Issue by jrupinski** [trilogy-libraries/trilogy#224]
### Problem:
Huge performance hit when switching to `trilogy://` from `mysql2://` on non-dev env.

### How to reproduce:
Replace `mysql2://` to `trilogy://` URL inside `database.yml` 

### Description:
On local machine/dev env, it works fine, but on staging and production, performance completely tanks, making the app unusable, and causing everything to be so slow that it's even crashing CI integration tests.

The same scenario happened when I tried to switch half a year ago.
I have no idea what is causing it, I could use some guidance here. Any ideas welcome. 🙏 

Contents of `database.yml`:
```
staging:
  primary:
    adapter: trilogy
    url: trilogy://app:AVNS_foobar@mysql-staging-do-user-12345-0.b.db.ondigitalocean.com:12345/foobar?ssl-mode=REQUIRED
    ssl: true
    ssl_mode: 'REQUIRED'
    tls_min_version: 3
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
  emails:
    adapter: trilogy
    url: trilogy://app:AVNS_foobar@external-emails-do-user-12345-0.b.db.ondigitalocean.com:12345/foobar?ssl-mode=REQUIRED
    ssl: true
    ssl_mode: 'REQUIRED'
    tls_min_version: 3
    migrations_paths: db/emails_migrate
    database_tasks: true
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
```
